#! /bin/sh

wal -a 70 -i Pictures/Wallpapers/wallpaper.jpg &
export GTK_THEME="Mari"
pgrep -x sxhkd > /dev/null || sxhkd &


bspc config normal_border_color '#02131a'
bspc config focused_border_color '#bcb4b9'
bspc config active_border_color '#02131a'

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 11

#bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 11 12 13 14 15 16 17 18 19 20

bspc config border_width         1
bspc config window_gap          32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

.config/polybar/launch.sh &
picom --config .config/picom/picom.conf --experimental-backends &


dunst -config .config/dunst/dunstrc &
xdo lower -N Polybar
